baseurl = "/"
languageCode = "en-us"
title = "A documentation website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Posts"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/frank0434/ApsimXLearn"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/frank0434"
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/jian-aka-frank-liu-9623379a/"

[params]
    author = "Jian (aka Frank) Liu"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"


